export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';

export const FETCH_HOSTELS = 'FETCH_HOSTELS';
export const SET_HOSTELS = 'SET_HOSTELS';
export const SET_BOOKMARK_HOSTELS = 'SET_BOOKMARK_HOSTELS';
export const SET_CURRENT_HOSTEL = 'SET_CURRENT_HOSTEL';
export const SEARCH_HOSTELS = 'SEARCH_HOSTELS';

export const BOOKMARK_HOSTEL = 'BOOKMARK_HOSTEL';
